### ISSUE TITLE
links to notes inside quotes doesn't work

### ISSUE THREAD

**Issue by danieltomasz** [jarodise/Dracula-for-Obsidian.md#1]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

This was reported on Obsidian forum
https://forum.obsidian.md/t/doesnt-work-inside-quotes-in-some-themes/626/6

Basically link to notes doesnt work  inside the quotes

![](https://forum.obsidian.md/uploads/default/original/1X/c319c9fe4c8c875bddb500cafb3738a272e27250.png)

```
<span class="cm-formatting-link cm-quote cm-quote-1">[[</span>`
<span class="cm-quote cm-quote-1 cm-hmd-internal-link">cycle of research</span>
<span class=" cm-formatting-link">]]</span>
```
The screenshot is a different theme but the same problem exist in Dracula :(

 Obsidian 0.6.4 on Mac

**Comment by jarodise** [comment]
thanks for reporting ,it has been fixed now.
