### ISSUE TITLE
Preview mode margins are narrower and clip the fold/unfold arrows

### ISSUE THREAD

**Issue by fcy** [jarodise/Dracula-for-Obsidian.md#12]
Obsidian 0.11.0
macOS 11.2.1

In edit mode it is all good:

<img width="831" alt="CleanShot 2021-02-27 at 20 42 10@2x" src="https://user-images.githubusercontent.com/105699/109408237-52dac600-793c-11eb-8822-4aab7a1d50f4.png">

But in preview it clips the fold/unfold arrows. Personally I think the margins should be the same.

![CleanShot 2021-02-27 at 20 43 33@2x](https://user-images.githubusercontent.com/105699/109408260-8ae20900-793c-11eb-90f6-25df566da803.png)

**Comment by jarodise** [comment]
hi, thanks for the feedback, I've pushed an update to fix this a while ago, please delete the theme and reinstall it to apply the change.

**Comment by fcy** [comment]
Oh I had no idea that I need to manually update it. Sorry for the noise.
