### ISSUE TITLE
Highlight has turned to light text color

### ISSUE THREAD

**Issue by pgalliford** [jarodise/Dracula-for-Obsidian.md#2]
[>](url
<img width="414" alt="Screen Shot 2020-06-01 at 3 29 46 pm" src="https://user-images.githubusercontent.com/60455813/83378670-c5a22980-a41c-11ea-879e-7c21582c986e.png">
) If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

**Comment by jarodise** [comment]
fixed
