### ISSUE TITLE
Dracula-for-Obsidian.md is looking different for me. I wonder why? 

### ISSUE THREAD

**Issue by Asparagus-inator** [jarodise/Dracula-for-Obsidian.md#4]
I noticed some UI discrepancies when I applied the Dracula theme.
<br>
Here is the reference image from how its supposed to look like:
![THEMES_reference](https://user-images.githubusercontent.com/69458045/90325283-3b457c80-dfac-11ea-9437-0f7875760115.png)
<br>
And this is what it looks like in my obsidian:
![what it looks like in my obsidian](https://user-images.githubusercontent.com/69458045/90325289-4698a800-dfac-11ea-8f63-6d96902eaf70.png)

<br><br>

- The code and quote block doesn't look the same with the photo reference for the theme. 
- The headings don't look bold.
- The highlight is on a different color.
- The bolded words gets colored in green.
- The in-line code is in a different color (but that's kind of okay, I like violet anyway).

Generally, some of the colors are mismatched and the font style is not applying as well. 

Just wanted to know if there is a fix I can do. Its still looks good as a theme but I would really like the code block to look like this:
![image](https://user-images.githubusercontent.com/69458045/90325467-91b3ba80-dfae-11ea-8e38-2963cec452fe.png)
 instead of how it shows right now because I always use it in my notes. 

Thank you in advance for the response!

**Comment by betegon** [comment]
Hi  @Asparagus-inator @jarodise 

Any update on this? the same happens to me (Ubuntu 20.04, Obsidian installed through snap).

Also, the left icon panel has dissapeared, so now I cannot access Obsidian settings.

Thank you for your help!
