### ISSUE TITLE
Tags are not readable in view mode

### ISSUE THREAD

**Issue by danieltomasz** [jarodise/Dracula-for-Obsidian.md#8]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

Obsidian 0.9.20, the tags in preview mode are impossible to read :( 

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/7980381/101552943-0a061780-39b4-11eb-8316-4ce0aca1c3ca.png">

**Comment by jarodise** [comment]
Hi Daniel, not sure why you are seeing that, on my end the tags look perfectly fine, there is no orange background to them and I don't remember every putting one there either, try download the newest version of the css file and relaunch again, let me know if that helps.

**Comment by danieltomasz** [comment]
Thanks! downloading from github css and replacing the previous one helped!
Previously I've changed  themes in obsidian (I checked several of the I a row), I wonder if I should report it to Obsidian team,
