### ISSUE TITLE
Problem with accessing  left sidebar ribbon - how to manually set it to always appear there

### ISSUE THREAD

**Issue by danieltomasz** [jarodise/Dracula-for-Obsidian.md#9]
Hi! Your theme is great but I don't like autohiding behaviour,it autohide too fast and I have problem with it to appear . 
I would like it to be always there, how I could change it manually in the css? 
<img width="24" alt="image" src="https://user-images.githubusercontent.com/7980381/101595469-ac91bb00-39f3-11eb-9ca2-3e65f0523931.png">
Moreover, sometimes after the ribbon autohide, there appear a visible artefact  in the left bottom corner
<img width="245" alt="image" src="https://user-images.githubusercontent.com/7980381/101595085-1a89b280-39f3-11eb-9f67-582efb2a8fda.png">

**Comment by aromeroc93** [comment]
I've got the same issue, I would prefer the side bar to be always visible. It is also not always appearing when hovering over the area.

**Comment by jarodise** [comment]
Hi, I'd more like to consider this a feature rather than an bug, since I myself prefer a cleaner work space, so hiding it would for sure reduce the amount of messiness and distractions, but if you prefer to leave it on all the time, there should be a way to tweak the CSS, I will try to find out how to achieve that and post it here.

**Comment by danieltomasz** [comment]
> Hi, I'd more like to consider this a feature rather than an bug, since I myself prefer a cleaner work space, so hiding it would for sure reduce the amount of messiness and distractions, but if you prefer to leave it on all the time, there should be a way to tweak the CSS, I will try to find out how to achieve that and post it here.

1. Yes I also treat this as a feature rather than a  bug :) I really like your theme, but the need of hoovering with mouse for a second is actullay distractive but I could still use your theme without that (and if you post a tweak to css it would be great)

2. I use MacoOS BigSur 11.0.1 with either Mac Screen or external screen, I mac external screen the lower corners are darker instead being lighter as in screenschoot (this is probaly due to the calibrartion of the monitor).

I dont know if this is issue related to your theme or how Obsidian(electrron) handle overlapping elements, but since other themes doesn't have autohiding bar this is not visible (it could be also not visible on some monitors I think, visibility of those corners vary between calibrations I am using  )

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/7980381/101812957-5ec4a200-3b1c-11eb-9786-08192f75a23b.png">
